site_name: Fatec Python
site_url: https://fatec-python.readthedocs.io/pt_BR/latest/

nav:
  - Home: index.md
  - "Lista 1": exercicios/listas/01.md
  - "MKDocs": mkdocs-help.md

theme:
  name: readthedocs
# plugins:
# - mkdocstrings:
#     enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
#     custom_templates: templates
#     default_handler: python
#     handlers:
#       python:
#         options:
#           show_source: false

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

copyright: |
  &copy; 2023 <a href="https://github.com/h4mn">h4mn</a> and contributors.